#!/usr/bin/env bash
# Drives the gotcha demos on the PSU ECE farm (katnemo).
#
# Usage:
#   bash sv_gotchas/_run_all_on_farm.sh                  # runs every demo dir
#   bash sv_gotchas/_run_all_on_farm.sh 01_DanglingWire  # runs one demo
#   bash sv_gotchas/_run_all_on_farm.sh 01_* 02_*        # runs a batch
#
# For each demo:
#   1. Mints a UTC timestamp on katnemo (so timestamps line up with the farm clock)
#   2. Creates ~/claude-runs/<STAMP>_<slug>/ on katnemo
#   3. scps the .sv and .do files there
#   4. Runs vsim -c -do "do run.do; quit -f" with the standard PATH and license env
#   5. scps the transcript back to the local demo dir
#   6. Writes MANIFEST.txt both locally and on the remote
#   7. Updates ~/claude-runs/latest symlink on katnemo to point at the most recent run

set -e -u -o pipefail

HOST="katnemo"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GOTCHA_ROOT="$REPO_ROOT/sv_gotchas"

# Build list of demo dirs to run.
if [[ $# -eq 0 ]]; then
  mapfile -t MODULES < <(cd "$GOTCHA_ROOT" && ls -d [0-9][0-9]_* 2>/dev/null | sort)
else
  MODULES=("$@")
fi

if [[ ${#MODULES[@]} -eq 0 ]]; then
  echo "No demo dirs to run." >&2
  exit 1
fi

echo "Will run on farm: ${MODULES[*]}"

OVERALL_OK=0
OVERALL_FAIL=0

for MOD in "${MODULES[@]}"; do
  MOD="${MOD%/}"
  LOCAL_DIR="$GOTCHA_ROOT/$MOD"
  if [[ ! -d "$LOCAL_DIR" ]]; then
    echo "[$MOD] SKIP -- no such directory: $LOCAL_DIR" >&2
    OVERALL_FAIL=$((OVERALL_FAIL + 1))
    continue
  fi

  echo
  echo "============================================================"
  echo "[$MOD] starting"
  echo "============================================================"

  STAMP=$(ssh "$HOST" 'date -u +%Y-%m-%dT%H-%M-%SZ')
  SLUG="$(echo "$MOD" | tr '[:upper:]' '[:lower:]')-sim"
  RUN_DIR="claude-runs/${STAMP}_${SLUG}"
  REMOTE_RUN_DIR="\$HOME/${RUN_DIR}"

  START_UTC=$(ssh "$HOST" 'date -u +%Y-%m-%dT%H:%M:%SZ')

  ssh "$HOST" "mkdir -p '${RUN_DIR}'"

  # scp every .sv and .do file in the demo dir
  scp "$LOCAL_DIR"/*.sv "$LOCAL_DIR"/*.do "$HOST:${RUN_DIR}/" > /dev/null

  # run on the farm
  ssh "$HOST" "
    set -e
    export PATH=/pkgs/mentor/questa/2021.3_1/questasim/bin:\$PATH
    export MGLS_LICENSE_FILE=1717@mentor-lic.cecs.pdx.edu
    export MTI_VCO_MODE=64
    cd '${RUN_DIR}'
    vsim -c -do 'do run.do; quit -f'
    ln -sfn '${STAMP}_${SLUG}' \$HOME/claude-runs/latest
  " || {
    echo "[$MOD] vsim failed on farm" >&2
    OVERALL_FAIL=$((OVERALL_FAIL + 1))
    continue
  }

  END_UTC=$(ssh "$HOST" 'date -u +%Y-%m-%dT%H:%M:%SZ')

  # pull transcript back
  scp "$HOST:${RUN_DIR}/transcript" "$LOCAL_DIR/transcript" > /dev/null

  # verify the pass line
  if grep -qE '^# No errors -- passed testbench' "$LOCAL_DIR/transcript"; then
    VERDICT="PASS"
    OVERALL_OK=$((OVERALL_OK + 1))
  else
    VERDICT="FAIL"
    OVERALL_FAIL=$((OVERALL_FAIL + 1))
  fi

  # write local MANIFEST.txt
  cat > "$LOCAL_DIR/MANIFEST.txt" <<EOF
module:       $MOD
host:         $HOST ($(ssh "$HOST" 'hostname'))
questa:       /pkgs/mentor/questa/2021.3_1/questasim/bin
start_utc:    $START_UTC
end_utc:      $END_UTC
remote_dir:   ~/$RUN_DIR
command:      vsim -c -do 'do run.do; quit -f'
verdict:      $VERDICT
notes:        Generated by sv_gotchas/_run_all_on_farm.sh
EOF

  # mirror MANIFEST.txt to remote
  scp "$LOCAL_DIR/MANIFEST.txt" "$HOST:${RUN_DIR}/MANIFEST.txt" > /dev/null

  echo "[$MOD] $VERDICT"
done

echo
echo "============================================================"
echo "summary: $OVERALL_OK passed, $OVERALL_FAIL failed"
echo "============================================================"

if [[ $OVERALL_FAIL -ne 0 ]]; then
  exit 1
fi
